// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentWaveApp.DataAccess;

#nullable disable

namespace RentWaveApp.DataAccess.Migrations
{
    [DbContext(typeof(RentWaveDbContext))]
    partial class RentWaveDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentWaveApp.Domain.Domain.Cast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Casts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            Name = "James Colton",
                            PartName = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            Name = "Lena Ford",
                            PartName = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 2,
                            Name = "Priya Shah",
                            PartName = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 3,
                            Name = "Boris Nikolov",
                            PartName = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 3,
                            Name = "Irina Volkova",
                            PartName = 4
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 4,
                            Name = "Grace Whitmore",
                            PartName = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 5,
                            Name = "Klaus Berger",
                            PartName = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 6,
                            Name = "Camille Laurent",
                            PartName = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 7,
                            Name = "Owen Marsh",
                            PartName = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 9,
                            Name = "Haruto Sato",
                            PartName = 7
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 10,
                            Name = "Diego Ramirez",
                            PartName = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 12,
                            Name = "Ji-ho Park",
                            PartName = 1
                        });
                });

            modelBuilder.Entity("RentWaveApp.Domain.Domain.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("time");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRestriction = 13,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = 7,
                            IsAvailable = true,
                            Language = 1,
                            Length = new TimeSpan(0, 2, 5, 0, 0),
                            Quantity = 3,
                            ReleaseDate = new DateTime(2021, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Last Signal"
                        },
                        new
                        {
                            Id = 2,
                            AgeRestriction = 0,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = 2,
                            IsAvailable = true,
                            Language = 1,
                            Length = new TimeSpan(0, 1, 45, 0, 0),
                            Quantity = 5,
                            ReleaseDate = new DateTime(2019, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bakery on Elm Street"
                        },
                        new
                        {
                            Id = 3,
                            AgeRestriction = 16,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = 3,
                            IsAvailable = true,
                            Language = 10,
                            Length = new TimeSpan(0, 2, 15, 0, 0),
                            Quantity = 2,
                            ReleaseDate = new DateTime(2018, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Shadows of Kolarov"
                        },
                        new
                        {
                            Id = 4,
                            AgeRestriction = 18,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = 4,
                            IsAvailable = true,
                            Language = 1,
                            Length = new TimeSpan(0, 1, 38, 0, 0),
                            Quantity = 4,
                            ReleaseDate = new DateTime(2022, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Silent Attic"
                        },
                        new
                        {
                            Id = 5,
                            AgeRestriction = 15,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = 5,
                            IsAvailable = true,
                            Language = 4,
                            Length = new TimeSpan(0, 1, 55, 0, 0),
                            Quantity = 0,
                            ReleaseDate = new DateTime(2020, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Midnight Ledger"
                        },
                        new
                        {
                            Id = 6,
                            AgeRestriction = 0,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = 6,
                            IsAvailable = true,
                            Language = 3,
                            Length = new TimeSpan(0, 1, 42, 0, 0),
                            Quantity = 6,
                            ReleaseDate = new DateTime(2017, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Paper Hearts in Lyon"
                        },
                        new
                        {
                            Id = 7,
                            AgeRestriction = 13,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = 8,
                            IsAvailable = true,
                            Language = 1,
                            Length = new TimeSpan(0, 2, 32, 0, 0),
                            Quantity = 3,
                            ReleaseDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Realm of Ashenfall"
                        },
                        new
                        {
                            Id = 8,
                            AgeRestriction = 0,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = 9,
                            IsAvailable = true,
                            Language = 1,
                            Length = new TimeSpan(0, 1, 20, 0, 0),
                            Quantity = 2,
                            ReleaseDate = new DateTime(2016, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Voices of the Reef"
                        },
                        new
                        {
                            Id = 9,
                            AgeRestriction = 0,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = 10,
                            IsAvailable = true,
                            Language = 6,
                            Length = new TimeSpan(0, 1, 30, 0, 0),
                            Quantity = 5,
                            ReleaseDate = new DateTime(2021, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kaiju Kindergarten"
                        },
                        new
                        {
                            Id = 10,
                            AgeRestriction = 16,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = 1,
                            IsAvailable = true,
                            Language = 2,
                            Length = new TimeSpan(0, 2, 8, 0, 0),
                            Quantity = 4,
                            ReleaseDate = new DateTime(2022, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Steel and Sand"
                        },
                        new
                        {
                            Id = 11,
                            AgeRestriction = 12,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = 3,
                            IsAvailable = true,
                            Language = 5,
                            Length = new TimeSpan(0, 1, 50, 0, 0),
                            Quantity = 3,
                            ReleaseDate = new DateTime(2019, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Understudy"
                        },
                        new
                        {
                            Id = 12,
                            AgeRestriction = 0,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = 2,
                            IsAvailable = true,
                            Language = 7,
                            Length = new TimeSpan(0, 1, 48, 0, 0),
                            Quantity = 5,
                            ReleaseDate = new DateTime(2020, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Comedy of Errors, Seoul"
                        });
                });

            modelBuilder.Entity("RentWaveApp.Domain.Domain.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RentedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Rentals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            RentedOn = new DateTime(2023, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnedOn = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 5,
                            RentedOn = new DateTime(2023, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 4,
                            RentedOn = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("RentWaveApp.Domain.Domain.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSubscript")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSubscript = true,
                            Name = "Basic"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSubscript = true,
                            Name = "Premium"
                        });
                });

            modelBuilder.Entity("RentWaveApp.Domain.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSubscriptionExpired")
                        .HasColumnType("bit");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 28,
                            CardNumber = "1111-2222",
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ana Petrova",
                            IsSubscriptionExpired = false,
                            SubscriptionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 34,
                            CardNumber = "3333-4444",
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Marko Ivanov",
                            IsSubscriptionExpired = false,
                            SubscriptionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Age = 41,
                            CardNumber = "5555-6666",
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Elena Dimova",
                            IsSubscriptionExpired = false,
                            SubscriptionId = 1
                        },
                        new
                        {
                            Id = 4,
                            Age = 23,
                            CardNumber = "7777-8888",
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Stefan Kolev",
                            IsSubscriptionExpired = true,
                            SubscriptionId = 2
                        });
                });

            modelBuilder.Entity("RentWaveApp.Domain.Domain.Cast", b =>
                {
                    b.HasOne("RentWaveApp.Domain.Domain.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("RentWaveApp.Domain.Domain.Rental", b =>
                {
                    b.HasOne("RentWaveApp.Domain.Domain.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentWaveApp.Domain.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentWaveApp.Domain.Domain.User", b =>
                {
                    b.HasOne("RentWaveApp.Domain.Domain.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
